import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { PromptValues } from "@norish/config/zod/server-config";
import { getPrompts } from "@norish/shared-server/config/server-config-loader";
import { resolveExistingWorkspacePath } from "@norish/shared-server/lib/workspace-paths";

import type { PromptConfigField, RetiredPromptDefaults } from "./overrides";
import { mergeWithDefaults } from "./overrides";

const PROMPTS_DIR = resolveExistingWorkspacePath(
  join("packages", "shared-server", "src", "ai", "prompts")
);

/** Every administrator-editable prompt, and the config field it is stored in. */
const PROMPT_FIELDS = {
  "recipe-extraction": "recipeExtraction",
  "image-extraction": "imageExtraction",
  "unit-conversion": "unitConversion",
  "nutrition-estimation": "nutritionEstimation",
  "auto-tagging": "autoTagging",
  "auto-categorization": "autoCategorization",
  "allergy-detection": "allergyDetection",
  "recipe-provenance": "recipeProvenance",
  "ingredient-linking": "ingredientLinking",
  "image-generation-brief": "imageGenerationBrief",
  "image-generation-style": "imageGenerationStyle",
  "ingredient-illustration-style": "ingredientIllustrationStyle",
} as const satisfies Record<string, PromptConfigField>;

export type PromptName = keyof typeof PROMPT_FIELDS;

function readDefaultPrompt(name: PromptName): string {
  return readFileSync(join(PROMPTS_DIR, `${name}.txt`), "utf-8");
}

/**
 * The prompts this release ships. The single source of every default: the
 * database only ever stores administrator overrides on top of these.
 */
export function loadDefaultPrompts(): PromptValues {
  return {
    recipeExtraction: readDefaultPrompt("recipe-extraction"),
    imageExtraction: readDefaultPrompt("image-extraction"),
    unitConversion: readDefaultPrompt("unit-conversion"),
    nutritionEstimation: readDefaultPrompt("nutrition-estimation"),
    autoTagging: readDefaultPrompt("auto-tagging"),
    autoCategorization: readDefaultPrompt("auto-categorization"),
    allergyDetection: readDefaultPrompt("allergy-detection"),
    recipeProvenance: readDefaultPrompt("recipe-provenance"),
    ingredientLinking: readDefaultPrompt("ingredient-linking"),
    imageGenerationBrief: readDefaultPrompt("image-generation-brief"),
    imageGenerationStyle: readDefaultPrompt("image-generation-style"),
    ingredientIllustrationStyle: readDefaultPrompt("ingredient-illustration-style"),
  };
}

/**
 * Default texts shipped by earlier releases (including the current ones).
 * The boot migration uses them to tell a seeded copy of an old default from
 * a prompt an administrator actually wrote. Regenerated by
 * `tooling/monorepo/scripts/generate-retired-prompt-defaults.mjs` whenever a
 * shipped prompt changes; a shared-server test fails when that is forgotten.
 */
export function loadRetiredDefaultPrompts(): RetiredPromptDefaults {
  const raw = readFileSync(join(PROMPTS_DIR, "retired-defaults.json"), "utf-8");

  return JSON.parse(raw) as RetiredPromptDefaults;
}

/**
 * The complete prompt set this deployment runs: administrator overrides over
 * shipped defaults, with the overridden fields named. What the admin surface
 * shows and every AI feature sends.
 */
export async function getEffectivePrompts(): Promise<{
  values: PromptValues;
  overriddenFields: PromptConfigField[];
}> {
  return mergeWithDefaults(await getPrompts(), loadDefaultPrompts());
}

/** Read one prompt, preferring the administrator's stored override. */
export async function loadPrompt(name: PromptName): Promise<string> {
  const { values } = await getEffectivePrompts();

  return values[PROMPT_FIELDS[name]];
}

export function fillPrompt(template: string, vars: Record<string, string>): string {
  let result = template;

  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), value);
  }

  return result;
}
